url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/" # the subpath of your site, e.g. /blog
permalink: pretty
email: "info@subseven.io"
global-title: "SubSeven &#xbb; Web Dev, Musician, Writer" # the name of your site, e.g. ACME Corp.
global-description: "Standing at the intersection of technology and life."
global-keywords: "globes, planet, interstellar"
include: ['.htaccess']
environment: development
recaptcha-key: 6Lcbpf0cAAAAAHtOgY1tO0_H-JAiDFeYZ32Ca6Au
timezone: America/Chicago

collections:
  now:
    output: true

sass:
    sass_dir: _sass
    style: compressed

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: /blog/:year/:month/:title/
      author: "Daniel Hernandez"

  - scope:
      path: ""
      type: "pages"
    values:
      author: "Daniel Hernandez"