url: https://subseven.io # the base hostname & protocol for your site, e.g. http://example.com
baseurl: / 
permalink: pretty
email: "info@subseven.io"

### Global SEO Settings ### 
### This information will be used as a fallback for all pages in your site if you do not set
### it on a per page basis.
title: "SubSeven &#xbb; Web Dev, Musician, Writer"
description: "I am a web developer and technical marketer based out of the midwest."
keywords: "subseven, subseven.io, sub7.dev, subseven.me"
image: /assets/img/sub7_def.png

language: "English"
index: "index, follow"
author: "Daniel Hernandez"
timezone: America/Chicago

include: 
  ['.htaccess', '_pages', '_cms']

exclude: 
  ['README.md', 'DOCUMENTATION.md', 'Gemfile.lock', 'Gemfile']  

collections:
  now:
    output: true

sass:
    sass_dir: _sass
    style: compressed

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: /blog/:year/:month/:title/
      author: "Daniel Hernandez"

  - scope:
      path: ""
      type: "pages"
    values:
      author: "Daniel Hernandez"