url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/" # the subpath of your site, e.g. /blog
email: "info@subseven.io"
global-title: "SubSeven &#xbb; Full-Stack Web Developer" # the name of your site, e.g. ACME Corp.
global-description: "This is the global site description that will show up when nothing is specified via the seo front matter"
global-keywords: "globes, planet, interstellar"
include: ['.htaccess']
environment: development

sass:
    sass_dir: _sass
    style: compressed

defaults:
  - 
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: /blog/:title
      author: "Daniel Hernandez"

  - 
    scope:
      path: ""
      type: "pages"
    values:
      author: "Daniel Hernandez"