url: https://subseven.io # the base hostname & protocol for your site, e.g. http://example.com
baseurl: / # the subpath of your site, e.g. /blog
permalink: pretty
email: "info@subseven.io"
global-title: "SubSeven &#xbb; Web Dev, Musician, Writer" # the name of your site, e.g. ACME Corp.
global-description: "I am a web developer and technical marketer based out of the midwest."
global-keywords: "subseven, subseven.io, sub7.dev, subseven.me"
global-image: /assets/img/sub7_def.png

language: "English"
index: "index, follow"
author: "Daniel Hernandez"
timezone: America/Chicago

include: 
  ['.htaccess']

exclude: 
  ['README.md', 'Gemfile.lock', 'Gemfile']  

collections:
  now:
    output: true

sass:
    sass_dir: _sass
    style: compressed

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: /blog/:year/:month/:title/
      author: "Daniel Hernandez"

  - scope:
      path: ""
      type: "pages"
    values:
      author: "Daniel Hernandez"