backend:
  name: github
  repo: subsevenx/jekyll-subseven.io
  branch: main
media_folder: "assets/img/uploads/"
publish_mode: "editorial_workflow"

collections:  
  
  #Blog Posts
  - label: "Blog Posts" 
    name: "blog-posts"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields: 
      - {label: "layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Permalink", name: "permalink", widget: "string"}
      - {label: "Date Posted", name: "date", widget: "datetime", default: "", date_format: "YYYY-MM-DD", time_format: "HH:mm:ss --600", format: "YYYY-MM-DD HH:mm:ss --600", picker_utc: false}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Excerpt", name: "excerpt", widget: "string",required: false} 
      - {label: "Featured Image", name: "featured-image", widget: "image", required: false}
      - {label: "Tags", name: "tags", widget: "list", allow_add: true, required: false}
      - {label: "Category", name: "category", widget: "list", max: 1, allow_add: true, required: false}
      - {label: "Body", name: "body", widget: "markdown"}

  #Now Collection
  - label: "Now Posts" 
    name: "now-posts"
    folder: "_now"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields: 
      - {label: "layout", name: "layout", default: null , widget: "hidden"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Hashtags", name: "tags", widget: "list"}
      - {label: "Date Posted", name: "date", widget: "datetime", default: "", date_format: "YYYY-MM-DD", time_format: "HH:mm:ss --600", format: "YYYY-MM-DD HH:mm:ss --600", picker_utc: false}
      - {label: "Body", name: "body", widget: "markdown"}
    
  # Navigation
  - label: "Navigation Settings"
    name: "nav-settings"
    editor:
      preview: false
    files:
      - label: "Menu Editor"
        name: "nav"
        file: "_data/nav.yml"
        fields:
          - label: "Navigation Menu Items"
            name: "menu"
            widget: "list"
            fields:
              - { label: "Name", name: "name", widget: "string" }
              - { label: "Link", name: "link", widget: "string" }
              - label: "Child" 
                name: "child" 
                widget: "list"
                fields: 
                - {label: "Name", name: "name", widget: "string"}
                - {label: "Link", name: "link", widget: "string"} 
      - label: "Footer Editor"
        name: "foot"
        file: "_data/nav.yml"
        fields: 
          - label: "Footer Menu Items"
            name: "footer"
            widget: "list"
            fields:
              - { label: "Name", name: "name", widget: "string" }
              - { label: "Link", name: "link", widget: "string" }