backend:
  name: github
  repo: subsevenx/jekyll-subseven.io
  branch: main
media_folder: "assets/img/uploads/"

collections:  
  - label: "Blog Posts" 
    name: "blog-posts"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields: 
      - label: "layout"
        name: "layout"
        widget: "hidden"
        default: "post"
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Excerpt"
        name: "excerpt"
        widget: "string" 
      - label: "Featured Image"
        name: "featured-image" 
        media_folder: assets/img/uploads/featured
        widget: image
      - label: "Tags"
        name: "tags"
        widget: "list"
        allow_add: true
      - label: "Category"
        name: "category"
        widget: "list"
        max: 1
        allow_add: true
      - label: "Body"
        name: "body"
        widget: "markdown"
  - label: "Now Posts" 
    name: "now-posts"
    folder: "_now"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields: 
      - label: "layout"
        name: "layout"
        default: "null"
        widget: "hidden"
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Hashtags"
        name: "tags"
        widget: "list"
      - label: "Date Posted"
        name: "date"
        widget: "datetime"
        default: ""
        date_format: "YYYY-MM-DD" 
        time_format: "HH:mm:ss --600" 
        format: "LLL"
        picker_utc: false
      - label: "Body"
        name: "body"
        widget: "markdown"

