backend:
  name: github
  repo: subsevenx/jekyll-subseven.io
  branch: lab-experiment

media_folder: "assets/img/uploads/"

collections:  
  
  #Blog Posts
  - label: "Blog Posts" 
    name: "blog-posts"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: false
    fields: 
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Featured Image", name: "featured", widget: "image", required: false}
      - {label: "Date Posted", name: "date", widget: "datetime", default: "", date_format: "YYYY-MM-DD", time_format: "HH:mm:ss --600", format: "YYYY-MM-DD HH:mm:ss --600", picker_utc: false}
      - {label: "Excerpt", name: "excerpt", widget: "string",required: false} 
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Category", name: "category", widget: "list", max: 1, allow_add: true, required: false}
      - {label: "Tags", name: "tags", widget: "list", allow_add: true, required: false}
      - {label: "SEO Title", name: "seo-title", widget: "string", required: false}
      - {label: "SEO Description", name: "seo-description", widget: "string", required: false}
      - {label: "SEO Keywords", name: "seo-keywords", widget: "string", required: false}
      - {label: "OpenGraph Title", name: "og-title", widget: "string", required: false}
      - {label: "OpenGraph Description", name: "og-description", widget: "string", required: false}
      - {label: "OpenGraph Image", name: "og-image", widget: "image", required: false}       

  #Now Collection
  - label: "Now Posts" 
    name: "now-posts"
    folder: "_now"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields: 
      - {label: "layout", name: "layout", default: null , widget: "hidden"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Hashtags", name: "tags", widget: "list"}
      - {label: "Date Posted", name: "date", widget: "datetime", default: "", date_format: "YYYY-MM-DD", time_format: "HH:mm:ss --600", format: "YYYY-MM-DD HH:mm:ss --600", picker_utc: false}
      - {label: "Body", name: "body", widget: "markdown"}
    
  # Navigation
  - label: "Navigation Settings"
    name: "nav-settings"
    editor:
      preview: false
    files:
      - label: "Nav & Footer Editor"
        name: "nav-footer-editor"
        file: "_data/nav.yml"
        widget: object
        fields:
          - label: "Navigation Menu Items"
            name: "menu"
            widget: "list"
            fields:
              - { label: "Name", name: "name", widget: "string" }
              - { label: "Link", name: "link", widget: "string" }
              - label: "Child" 
                name: "child" 
                widget: "list"
                fields: 
                - {label: "Name", name: "name", widget: "string"}
                - {label: "Link", name: "link", widget: "string"} 
          - label: "Footer Menu Items"
            name: "footer"
            widget: "list"
            fields: 
              - { label: "Name", name: "name", widget: "string" }
              - { label: "Link", name: "link", widget: "string" }

  - label: "Page Content Editor" 
    name: "page-content-editor"
    editor:
      preview: false
    files:
      - label: "Home Page"
        name: "index"
        file: "index.md"
        fields: 
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
      - label: "About Page"
        name: "about"
        file: "about.md"
        fields: 
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
      - label: "Now Page"
        name: "now"
        file: "now.html"
        fields: 
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Page Blurb", name: "blurb", widget: "text" } 
      - label: "Contact Page"
        name: "contact"
        file: "contact.html"
        fields: 
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Page Blurb", name: "blurb", widget: "text" }     
      - label: "Blog Page"
        name: "blog"
        file: "blog.html"
        fields: 
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Page Blurb", name: "blurb", widget: "text" }
      - label: "Resume Page"
        name: "resume"
        file: "html.html"
        fields: 
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Page Blurb", name: "blurb", widget: "text" }
      - label: "Portfolio Page"
        name: "nav-footer-editor"
        file: "_data/portfolio.yml"
        widget: object
        fields:
          - label: "Portfolio Item"
            name: "list"
            widget: "list"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Image", name: "img", widget: "image" }
              - { label: "Description", name: "blurb", widget: "text" }