name: Remote Deploy
on: [push]
jobs: 
  step-one: 
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ssh.ssio.dev
          username: subseven
          key: ${{ secret.GREEKTOWN }}
          port: 22
          script: | 
            cd /home/subseven/deploy.git/hooks
            bash post-receive
            git status
